export const litScreenSpaceRaymarchFragmentTemplate = `#version 300 es
precision highp float;
#pragma DEFINES
layout(std140) uniform ubCommon{float uTime;float uDeltaTime;vec4 uViewport;};layout(std140) uniform ubTransformations{mat4 uWorldMatrix;mat4 uViewMatrix;mat4 uProjectionMatrix;mat4 uNormalMatrix;mat4 uInverseWorldMatrix;mat4 uViewProjectionMatrix;mat4 uInverseViewMatrix;mat4 uInverseProjectionMatrix;mat4 uInverseViewProjectionMatrix;mat4 uTransposeInverseViewMatrix;};layout(std140) uniform ubCamera{vec3 uViewPosition;vec3 uViewDirection;float uNearClip;float uFarClip;float uAspect;float uFov;};layout(std140) uniform ubTimeline{float uTimelineTime;float uTimelineDeltaTime;};
#pragma BLOCK_BEFORE_RAYMARCH_CONTENT
#define PI 3.14
#define PI2 6.28
vec2 o(vec2 u,vec2 o){return u.x<o.x?u:o;}mat2 o(float u){float v=sin(u),f=cos(u);return mat2(f,v,-v,f);}vec3 opRe(vec3 u,float o){return u-o*round(u/o);}vec2 opRo(vec2 u,float v){return u*o(-v);}vec3 opTr(vec3 u,vec3 o){return u-o;}vec3 u(vec3 u,vec3 o){return u/o;}float n(float u,vec3 v){return u*min(v.x,min(v.y,v.z));}vec2 n(vec2 u){float v=PI/10.-atan(u.x,u.y),f=PI*2./10.;v=floor(v/f)*f;return opRo(u,-v);}float opSm(float u,float v,float o){float f=clamp(.5+.5*(v-u)/o,0.,1.);return mix(v,u,f)-o*f*(1.-f);}float dfSp(vec3 u,float o){return length(u)-o;}float dfRb(vec3 u,vec3 o,float v){vec3 f=abs(u)-o;return length(max(f,0.))+min(max(f.x,max(f.y,f.z)),0.)-v;}float dfBo(vec3 u,vec3 o){vec3 v=abs(u)-o;return length(max(v,0.))+min(max(v.x,max(v.y,v.z)),0.);}float dfTo(vec3 u,vec2 o){return length(vec2(length(u.xz)-o.x,u.y))-o.y;}float n(vec3 u,float o,float v){vec2 f=vec2(length(u.xz)-2.*o+.05,abs(u.y)-v);return min(max(f.x,f.y),0.)+length(max(f,0.))-.05;}float opWi(vec3 v,vec3 f,float o,vec2 m){v=opTr(v,vec3(m.xy,0));v.xy=opRo(v.xy,o);v.yz=opRo(v.yz,PI*.5);v=u(v,f);float z=n(v,1.,.1);return n(z,f);}vec2 opBu(vec3 u,float o){u/=1.4;vec3 v=u;v.yz=opRo(v.yz,-PI*.5);vec2 f=vec2(10,.6);v.x=abs(v.x);v.xz=opRo(v.xz,PI*sin(sin(uTimelineTime*f.x+o)*cos(uTimelineTime*f.y+o))*.3);float m=opWi(v,vec3(.4,.3,.24)*.2,PI*-.3,vec2(.5,.4)*.2),z=opWi(v,vec3(.32,.3,.2)*.2,PI*.3,vec2(.4,-.4)*.2);return vec2(min(m,z),0);}vec2 opFl(vec3 v,float f){vec2 m=vec2(1e4,-1e4);v/=1.;v.y-=-.8;float r=.1;r=sin(uTimelineTime*1.4+.2+f)*.5;float z=-.1;z=cos(uTimelineTime*1.6+.1+f)*-.5;float x=v.y*sin(v.y*r),y=v.y*sin(v.y*z),s=sin(1.12*r)*.28,P=sin(1.12*z)*.28;mat2 d=o(-1.12*r),t=o(1.12*z);vec3 l=v;l=opTr(l,vec3(x,.28,y));float G=n(l,.015,.28);m=o(m,vec2(G,1));vec3 i=v;i=opTr(i,vec3(s,.56,P));i.yz=opRo(i.yz,PI*.5);i.xz*=d;i.yz*=t;i.xy=n(i.xy);i=opTr(i,vec3(0,.2,sin(i.y*5.)*.105));i.yz=opRo(i.yz,PI*.5);vec3 S=vec3(.08,.2,.2);i=u(i,S);float c=n(i,.4,.01);c=n(c,S);m=o(m,vec2(c,2));vec3 B=v;B=opTr(B,vec3(s,.59,P));float e=dfSp(B,.04);return o(m,vec2(e,3));}float opDb(float u,float v,float f,float m,float o,float z){return mix(mix(mix(v,f,smoothstep(0.,.25,u)),mix(f,m,smoothstep(.25,.5,u)),smoothstep(.25,.5,u)),mix(mix(m,o,smoothstep(.5,.75,u)),mix(o,z,smoothstep(.75,1.,u)),smoothstep(.5,.75,u)),smoothstep(.5,1.,u));}float opTb(float u,float v,float f,float o){return mix(mix(v,f,smoothstep(0.,.5,u)),mix(f,o,smoothstep(.5,1.,u)),smoothstep(.5,1.,u));}
#define BN 16
#define FS 1.
#define CS.35
#define MS.25
uniform vec3 uCP,uBPs[BN],uGPs[4];uniform float uGS;uniform vec4 uGSs[4];uniform float uOMR;uniform vec3 uORo;float u(vec3 v){return sin(v.x*4.+uTimelineTime*3.4)*.07+cos(v.y*3.+uTimelineTime*3.2)*.07+sin(v.z*3.5+uTimelineTime*3.)*.07;}float dfMC(vec3 u){return dfSp(u,FS);}float diMAt(vec3 u){return 1.-smoothstep(1.,1.8,length(u-uCP));}float dfMB(vec3 v,float f){for(int o=0;o<BN;o++){float m=dfSp(opTr(v,uBPs[o].xyz),CS);f=opSm(f,m,MS);}f+=u(v)*diMAt(v)*uGS;return f;}float dfMBs(vec3 u){float v=dfSp(opTr(u,uCP),FS*uGS);return dfMB(u,v);}vec2 opMo(vec2 v,vec2 u,float f){return mix(v,u,f);}vec2 o(vec3 u,float v,float f){vec3 o=mod(u*f,2.)-1.;f*=3.;vec3 m=abs(1.-3.*abs(o));float z=(min(max(m.x,m.y),min(max(m.y,m.z),max(m.z,m.x)))-1.)/f;return vec2(max(v,z),f);}float dfMe(vec3 v){v/=.5;float u=dfBo(v,vec3(1));vec2 f=vec2(u,1);f=o(v,f.x,f.y);f=o(v,f.x,f.y);f=o(v,f.x,f.y);return f.x;}
#pragma RAYMARCH_SCENE
vec3 v(vec3 u){vec3 v=vec3(dfScene(u+vec3(1e-4,0,0)).x-dfScene(u+vec3(-1e-4,0,0)).x,dfScene(u+vec3(0,1e-4,0)).x-dfScene(u+vec3(0,-1e-4,0)).x,dfScene(u+vec3(0,0,1e-4)).x-dfScene(u+vec3(0,0,-1e-4)).x);return normalize(v);}vec3 n(vec2 u,vec3 v,float f,float o){vec2 m=u*2.-1.;float z=tan(f*3.141592/180.*.5);vec3 s=v,x=normalize(cross(s,vec3(0,1,0)));return normalize(z*o*x*m.x+normalize(cross(x,s))*z*m.y+v);}float u(float u,float v,float o){return(u+v)/(v-o);}float v(float v,float u,float o){float f=u*v;return-f/(o*(v-1.)-f);}void v(float v,float u){if(v<u)discard;}uniform float uMetallic,uRoughness;uniform int uShadingModelId;
#pragma APPEND_UNIFORMS
uniform sampler2D uDepthTexture;uniform float uTargetWidth,uTargetHeight;
#ifdef USE_ALPHA_TEST
uniform float uAlphaTestThreshold;
#endif
in vec2 vUv;in vec3 vWorldPosition;
#define SHADING_MODEL_NUM 3.
struct GBufferA{vec3 baseColor;};struct GBufferB{vec3 normal;float shadingModelId;};struct GBufferC{float metallic;float roughness;};struct GBufferD{vec3 emissiveColor;};vec4 x(vec3 v,int u){float f=float(u)/SHADING_MODEL_NUM;return vec4(v*.5+.5,f);}layout(location=0) out vec4 outGBufferA;layout(location=1) out vec4 outGBufferB;layout(location=2) out vec4 outGBufferC;layout(location=3) out vec4 outGBufferD;void main(){vec4 f=vec4(0,0,0,1);vec3 o=vec3(0,0,1),m=uViewPosition,z=n(vUv,uViewDirection,uFov,uAspect);vec2 i=vec2(0);float r=uNearClip;vec3 y=m;for(int d=0;d<100;d++){y=m+z*r;i=dfScene(y);r+=i.x;if(r>uFarClip||i.x<=1e-4)break;}if(i.x>1e-4)discard;float s=texelFetch(uDepthTexture,ivec2(gl_FragCoord.xy),0).x,P=v(s,uNearClip,uFarClip),l=u((uViewMatrix*vec4(y,1)).z,uNearClip,uFarClip);if(l>=P)discard;vec4 d=uProjectionMatrix*uViewMatrix*vec4(y,1);gl_FragDepth=d.z/d.w*.5+.5;if(i.x>0.)o=v(y);
#ifdef USE_ALPHA_TEST
v(f.w,uAlphaTestThreshold);
#endif
f.xyz=pow(f.xyz,vec3(2.2));outGBufferA=vec4(f.xyz,1);outGBufferB=x(o,uShadingModelId);outGBufferC=vec4(uMetallic,uRoughness,0,1);outGBufferD=vec4(vec4(1).xyz,1);}`;