

export const FOLLOWERS_ACTOR_NAME_A = 'F_A';
export const FOLLOWERS_ACTOR_NAME_B = 'F_B';
export const FOLLOWERS_ACTOR_NAME_C = 'F_C';


export const ATTRACTOR_TARGET_BOX_A_MESH = 'AB_AM';
export const ATTRACTOR_TARGET_BOX_B_MESH = 'AB_BM';

export const ATTRACTOR_TARGET_SPHERE_ACTOR_A_NAME = 'AS_A';
export const ATTRACTOR_TARGET_SPHERE_ACTOR_B_NAME = 'AS_B';

export const ATTRACTOR_ORBIT_MOVER_A = 'O_A';
export const ATTRACTOR_ORBIT_MOVER_B = 'O_B';
export const ATTRACTOR_ORBIT_MOVER_C = 'O_C';

export const DEPTH_OF_FIELD_TARGET_ACTOR_NAME = 'FT';
