
export const MAIN_CAMERA_ACTOR_NAME = 'MC';

export const DIRECT_LIGHT_ACTOR_NAME = 'DL';

export const SPOT_LIGHT_ACTOR_NAME_A = 'SL_A';
export const SPOT_LIGHT_ACTOR_NAME_B = 'SL_B';

export const ORIGIN_FORGE_ACTOR_NAME = 'OF';

export const ORIGIN_FORGE_GATHER_CHILD_ACTOR_NAME_1 = 'OF_G1';
export const ORIGIN_FORGE_GATHER_CHILD_ACTOR_NAME_2 = 'OF_G2';
export const ORIGIN_FORGE_GATHER_CHILD_ACTOR_NAME_3 = 'OF_G3';
export const ORIGIN_FORGE_GATHER_CHILD_ACTOR_NAME_4 = 'OF_G4';

export const FOLLOWERS_ACTOR_NAME_A = 'F_A';
export const FOLLOWERS_ACTOR_NAME_B = 'F_B';
export const FOLLOWERS_ACTOR_NAME_C = 'F_C';


export const ATTRACTOR_TARGET_BOX_ROOT_ACTOR_A = 'AB_A';
export const ATTRACTOR_TARGET_BOX_ROOT_ACTOR_B = 'AB_B';

export const ATTRACTOR_TARGET_SPHERE_ACTOR_A_NAME = 'AS_A';
export const ATTRACTOR_TARGET_SPHERE_ACTOR_B_NAME = 'AS_B';

export const ATTRACTOR_ORBIT_MOVER_A = 'O_A';
export const ATTRACTOR_ORBIT_MOVER_B = 'O_B';
export const ATTRACTOR_ORBIT_MOVER_C = 'O_C';

export const DEPTH_OF_FIELD_TARGET_ACTOR_NAME = 'FT';

export const FLOOR_ACTOR_NAME = 'FL';

export const POST_PROCESS_ACTOR_NAME = 'PP';
